[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
board_build.f_cpu = 80000000L
board_build.partitions = huge_app.csv
board_build.hwids = 10C4, EA60
framework = arduino
extra_scripts = pre:scripts/patch_dependencies.py
upload_speed = 921600
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++2a
	-D SMALL_RTC_NO_DS3232=1
	-D PRIVATE=0
    -D RELEASE=\"v1.2.1\"
	-Ofast
lib_deps = 
	GuruSR/SmallRTC@2.4.7
	PaulStoffregen/Time@1.6.1
	adafruit/Adafruit BusIO@1.17.4
	adafruit/Adafruit GFX Library@1.12.6
	https://github.com/orbitalair/Rtc_Pcf8563.git#1.0.3
	zinggjm/GxEPD2@1.6.9
	arduino-libraries/NTPClient@3.2.1
	rpolitex/ArduinoNvs@2.10.0
